"""init-user

Revision ID: 212fdb401ebc
Revises: 
Create Date: 2024-07-14 07:33:51.526982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212fdb401ebc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=256), nullable=True, comment='密码'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
