"""新增商品分类

Revision ID: 35dc523a3177
Revises: 4ff7158df919
Create Date: 2024-03-10 03:41:02.999136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35dc523a3177'
down_revision = '4ff7158df919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesscategories',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='大类名称'),
    sa.Column('img', sa.String(length=128), nullable=True, comment='大类图片'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesscategories_id'), 'businesscategories', ['id'], unique=False)
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_businesscategories_id'), table_name='businesscategories')
    op.drop_table('businesscategories')
    # ### end Alembic commands ###
