"""调整用户表

Revision ID: 4ff7158df919
Revises: d59e8be068c3
Create Date: 2024-03-10 03:14:33.141808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ff7158df919'
down_revision = 'd59e8be068c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True, comment='项目'))
    op.add_column('users', sa.Column('mobile', sa.String(length=11), nullable=True, comment='手机号'))
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True, comment='密码'))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=50), nullable=True, comment='密码'))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=50), nullable=True, comment='邮箱'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
