"""新增商品分类

Revision ID: 525389bd0828
Revises: 35dc523a3177
Create Date: 2024-03-10 03:54:37.242637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '525389bd0828'
down_revision = '35dc523a3177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('name', sa.String(length=20), nullable=True, comment='大类名称'),
    sa.Column('img', sa.String(length=128), nullable=True, comment='大类图片'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('good_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='分类名称'),
    sa.Column('img', sa.String(length=128), nullable=True, comment='分类图片'),
    sa.Column('starting_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('business_categories_id', sa.Integer(), nullable=True, comment='business_categories_id'),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_categories_id'], ['business_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_businesscategories_id', table_name='businesscategories')
    op.drop_table('businesscategories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesscategories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True, comment='大类名称'),
    sa.Column('img', mysql.VARCHAR(length=128), nullable=True, comment='大类图片'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_businesscategories_id', 'businesscategories', ['id'], unique=False)
    op.drop_table('good_type')
    op.drop_table('business_categories')
    # ### end Alembic commands ###
