"""备注

Revision ID: 9ae52bcde376
Revises: ceab1be7dc5e
Create Date: 2024-08-13 23:01:49.416636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ae52bcde376'
down_revision = 'ceab1be7dc5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='博客标题'),
    sa.Column('content', sa.String(length=2000), nullable=False, comment='博客内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_permissions',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='数据权限名'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='数据权限描述'),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='部门名'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='部门描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menus',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='菜单名'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='菜单描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buttons',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='按钮名'),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True, comment='按钮描述'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_data_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('data_permission_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_permission_id'], ['data_permissions.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'data_permission_id')
    )
    op.create_table('role_menu_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('role_button_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('button_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'button_id')
    )
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('permissions', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='状态'))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_comment='用户名')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False,
               existing_comment='密码')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True,
               existing_comment='密码')
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_comment='用户名')
    op.drop_column('users', 'department_id')
    op.drop_column('roles', 'is_deleted')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('permissions', 'is_deleted')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    op.drop_table('role_button_permissions')
    op.drop_table('role_menu_permissions')
    op.drop_table('role_data_permissions')
    op.drop_table('buttons')
    op.drop_table('menus')
    op.drop_table('departments')
    op.drop_table('data_permissions')
    op.drop_table('blogs')
    # ### end Alembic commands ###
