"""init

Revision ID: d59e8be068c3
Revises: 
Create Date: 2024-03-10 02:35:53.357745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59e8be068c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=50), nullable=True, comment='密码'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
