"""用户表加入时间字段

Revision ID: e3ec10aeccef
Revises: 08e52ff4876a
Create Date: 2024-03-10 04:12:15.850179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3ec10aeccef'
down_revision = '08e52ff4876a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='名称',
               existing_comment='项目',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='项目',
               existing_comment='名称',
               existing_nullable=True)
    # ### end Alembic commands ###
